base: 'https://%env(FRONTEND_DOMAIN)%/'
baseVariants:
  -
    base: 'https://chanathake-locations.ddev.site/'
    condition: 'host == "chanathale-locations.ddev.site"'
dependencies:
  - typo3/fluid-styled-content
  - chanathale/chanathale-locations-dev
  - chanathale/chanathale-locations
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=2'
languages:
  -
    title: Deutsch
    enabled: true
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: ''
    hreflang: de
    direction: ltr
    flag: de
    languageId: 0
    base: /
logo: logotext
rootPageId: 1
websiteTitle: ''
